name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: yarn && yarn build && yarn test
      - name: report
        uses: codecov/codecov-action@v1.0.6
        env:
          CI: true
